export enum UserType {
  MASTER = 'MASTER',
  DEVELOPER = 'DEVELOPER',
  FINANCE = 'FINANCE',
  SUPER = 'SUPER',
  SUPPORT = 'SUPPORT',
  DUNGEON_MASTER = 'DUNGEON_MASTER',
  ADMIN = 'ADMIN',
  SUPPORT_MANAGER = 'SUPPORT_MANAGER',
}
